lsi: false
safe: true
baseurl: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: minima 
# remote_theme: benbalter/retlab
# theme: cayman

title: Cyber Security & Development Blog
author:
  name: ix76y
  email: TroubledWaffle@protonmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Welcome to my github blog. I love cyber security and generally anything that has to do with coding. 
  My favorite languages include: C, Rust, Python, Assembly, and Swift. 