lsi: false
safe: true
baseurl: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
# theme: minima 
# remote_theme: benbalter/retlab
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme